#!/bin/bash

echo "🌐 VEGA.ai Cloud Deployment Guide"
echo "================================="
echo ""
echo "🎯 Your domain: imacc.iamvega.ai"
echo ""
echo "📋 FREE Hosting Options:"
echo ""
echo "1. 🚂 RAILWAY (Recommended)"
echo "   • Visit: https://railway.app"
echo "   • Connect GitHub repo"
echo "   • Deploy both services"
echo "   • Add custom domain: imacc.iamvega.ai"
echo ""
echo "2. 🎨 RENDER"
echo "   • Visit: https://render.com"
echo "   • Create Web Service from Git"
echo "   • Docker runtime"
echo ""
echo "3. ✈️  FLY.IO"
echo "   • Visit: https://fly.io"
echo "   • Install flyctl"
echo "   • fly launch"
echo ""
echo "4. 🌊 DIGITAL OCEAN APP PLATFORM"
echo "   • Visit: https://www.digitalocean.com/products/app-platform"
echo "   • $5/month for basic app"
echo ""
echo "📝 Required Environment Variables:"
echo "   OPENAI_API_KEY=your_key_here"
echo "   HEYGEN_API_KEY=your_key_here"
echo ""
echo "🔗 After deployment, point imacc.iamvega.ai to the provided URL"
