# Railway.toml - Railway deployment configuration
[build]
  builder = "docker"

[deploy]
  healthcheck_path = "/health"
  start_command = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[[services]]
  name = "backend"
  dockerfile = "Dockerfile"
  
  [services.variables]
    PORT = "8000"
    PYTHONPATH = "/app"

[[services]]
  name = "frontend"
  dockerfile = "frontend/Dockerfile"
