version: '3.8'

services:
  # Frontend service only
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vega-frontend-only
    restart: unless-stopped
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge
