version: '3.8'

services:
  # Backend service with minimal dependencies
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vega-backend-only
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - ./agenbotc/.env
    volumes:
      - ./agenbotc/uploads:/app/agenbotc/uploads
      - ./agenbotc/vectorstore:/app/agenbotc/vectorstore
      - ./logs:/app/logs
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis for backend caching
  redis:
    image: redis:7-alpine
    container_name: vega-redis-backend
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:

networks:
  default:
    driver: bridge
